---
title: "607countproject"
author: "jim lung"
date: "2017¦~3¤ë20¤é"
output: html_document
---

```{r }
library(RCurl)
library(stringr)
library(bitops)
```


```{r }
#jobskills <- readLines("https://raw.githubusercontent.com/jmehta753/MSDA_JM/master/DATA607/Project3/JobSkills.txt")
jobskills <- c("Python","R","analytics","machine learning","programming","team","statistics","SQL","sql","communication","big data","design","Hadoop","Java","research","creative","math","mathematic","MATLAB","predictive analytics","SAS","Modelling","C++","builders at heart","experienced","outgoing","self-motivated professional","creating analytics programs","thought leadership" )


jobskills
write.table(jobskills, "jobskills.txt", sep="\t")

```


```{r }
text <- c("


Join a firm that values diversity & flexible working practices

¡EEnergetic and Inspirational Team

¡EApply Assurance skills while being challenged to think laterally

 
If you have demonstrated strengths in visual communication and design, or business analytics, working at PwC can provide you with training and exposure in both delivery of business insight and assurance to give you the opportunity to build out your skills and position yourself for a highly rewarding career.
 
PwC is a firm committed to collaboration and strong relationships that help our clients and our people realise their ambitions. Well known for our technical excellence, we are also a firm brimming with energetic and inspirational people who want to build a diverse and enduring career in a progressive, global network.

About the role:
PwC's Assurance practice provides assurance on the financial performance and operations of businesses and is the world¡¦s leading practice of its kind. We are making significant investments in techniques and technologies to equip our Assurance staff with the best tools and processes in the market.
Due to the ongoing success of the group, we're looking for an experienced Senior Consultant to join the team in Perth. Reporting to a Data Analytics Manager and Partner, the Senior Consultant will build client relationships and deliver work of value to our clients. As a member of our team, you would be key in the engagement and delivery of bespoke analytic projects and a leader for us in the development of our data visualisation practices; at the same time building a range of business and technical skills to become a well-rounded Data Scientist.
 
Using innovative software you will provide broader assurance and deeper insights to some of the leading organisations in Australia. 
 
You will have the opportunity to use a creative, entrepreneurial and consulting mind set to revolutionise the way our work is performed and our findings are delivered to clients. 

 We are working to transform PwC's Assurance practice, using data analytics to gain better business insights for our clients and an improved engagement experience for our clients and our people. 
 We are employing leading data visualisation techniques (using tools such as Qlik, and Tableau) in the presentation of our analytical outputs. Our projects cover a wide range of business contexts and give our people exposure to business leaders and decision makers from an early stage in their career.
 
Skills/experience required:
¡EExcellent verbal and written communication skills

¡EExisting strong expertise and demonstrated passion in Data Visualisation and/or Visual design

¡EExperience working with data across several enterprise information platforms, specifically extracting and cleansing data

¡EHigh level of proficiency in Excel

¡EExperience in SQL would be a key advantage but not essential if you have a demonstrated flair for data visualisation and problem solving and willingness to learn and become proficient in ACL, Alteryx and/or SQL.

¡EExperience working in a finance orientated area is beneficial 

¡EA degree-level qualification in a ¡¥quantitative¡¦ field such as; Engineering, Econometrics, Applied Mathematics, Science, Finance or Commerce; or alternatively a qualification in ¡¥Computer Science¡¦ or ¡¥Computer Engineering¡¦, would be advantageous. Or a degree-level qualification in Design with subsequent study showing an interest and commitment to STEM fields.

¡EUnderstanding of basic business processes

¡EExperience managing concurrent work streams/deliverables


 

Key behaviours required:

 
¡EDrive and enthusiasm ¡V energetic, motivated and passionate about the Firm and the role

¡ECapacity and willingness to share your expertise and teach others

¡EProfessionalism ¡V professional approach, confidentiality, in line with the Firm¡¦s guidelines

¡ECommunication skills ¡V able to communicate effectively with internal and external clients

¡EStrong attention to detail

¡EResilient - able to handle high levels of conflict and pressure, whilst remaining calm

¡EWilling to have a go, try new things and be creative 


Ability to work autonomously and as part of a team

 

The offer at PwC: 

 

PwC is one of Australia's leading professional services firms, bringing the power of our global network of firms in 157 countries to help Australian businesses, not-for-profit organizations and governments assess their performance and improve the way they work. 
 

 The PwC Australia experience will offer you the opportunity to work with the best people and technology, flexible working arrangements and activity based working, a diverse workplace and embedded cultural values in everything we do. We offer reward and recognition for your efforts so you can realize your potential through coaching and career development.

Diversity:

We work in a changing world which offers great opportunities for people with diverse backgrounds and experiences. We seek to attract and employ the best people from the widest talent pool as well as those who reflect the diverse nature of our society. And we aim to encourage a culture where people can be themselves and be valued for their strengths. This is why we¡¦re committed to conversations about flexibility that work for you and our clients. Creating value through diversity iswhat makes us strong as a business. http://www.pwc.com.au/about-us/diversity-and-inclusion

 

Next step:

 
Ready for the opportunity of a lifetime? Apply online now - http://www.pwc.com.au/careers/index.htm
 



c 2015 PwC. All rights reserved. PwC refers to the PwC network and/or one or more of its member firms, each of which is a separate legal entity. Please see www.pwc.com/structure for further details.


")

text

```


```{r }
for (skill in jobskills) {
  print(skill)
  print(lapply(skill, str_count, string=text))
}


```


```{r }



```
